### ISSUE TITLE
HA sign in to Tick Tick with Google credentials

### ISSUE THREAD

**Issue by 6arcaxavi** [BeryJu/hass-ticktick#1]
Hi! 
Tried to sign in with my Google credentials, since I'm registered with that in Tick Tick, but none of the combination worked that I put in. 
Any ideas how to try it?

**Comment by BeryJu** [comment]
Hi, thanks for using my integration!

Since TickTick doesn't publish any API Documentation, the current API is based on reverse-engineering of the Web-Client. OAuth via Google/etc could probably implemented, but frankly, its a lot of effort.

Is there any reason you can't add a Password to your Account under Settings -> Profile? That would work with this.

Cheers

**Comment by 6arcaxavi** [comment]
Thanks for the quick answer, and for the integration of course.
I didn't really know that this is a possibility, it worked like a charm.

Thanks again!
